/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;
import control.AdmConsulta_Medica;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.print.Printable;
import java.awt.*;
import java.awt.print.*;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import javafx.print.PrinterJob.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author DoTa_
 */

public class EX_MICRO extends javax.swing.JFrame implements Printable
{
private AdmConsulta_Medica  admConsulta_Medica= AdmConsulta_Medica.getAdmConsulta_Medica();
   
    /**
     * Creates new form EX_MICRO
     */
    public EX_MICRO() {
        initComponents();

        this.setLocationRelativeTo(null);
        admConsulta_Medica.llenarCriteriok(jHematies,jPlacitos,jBacterias,jCilindros,jCristales,jCel,jFil);
        txtpaciente.setText(""+admConsulta_Medica.getPacientes().
        get(admConsulta_Medica.getIndexPaciente()).getNombre()+" "+admConsulta_Medica.getPacientes().get(admConsulta_Medica.getIndexPaciente()).getApellido());
        //Color fondoPrincipal = new Color(140, 174, 212);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimir = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpaciente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jHematies = new javax.swing.JTextField();
        jBacterias = new javax.swing.JTextField();
        jCristales = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jFil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCilindros = new javax.swing.JTextField();
        jCel = new javax.swing.JTextField();
        jPlacitos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imprimir.setBackground(new java.awt.Color(255, 255, 255));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("Microscopico");
        jTextField9.setBorder(null);

        jLabel5.setText("Cristales:");

        txtpaciente.setEditable(false);
        txtpaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtpaciente.setBorder(null);

        jLabel6.setText("Cilindros:");

        jLabel7.setText("Bacterias:");

        jHematies.setEditable(false);
        jHematies.setBackground(new java.awt.Color(255, 255, 255));
        jHematies.setBorder(null);

        jBacterias.setEditable(false);
        jBacterias.setBackground(new java.awt.Color(255, 255, 255));
        jBacterias.setBorder(null);

        jCristales.setEditable(false);
        jCristales.setBackground(new java.awt.Color(255, 255, 255));
        jCristales.setBorder(null);

        jFil.setEditable(false);
        jFil.setBackground(new java.awt.Color(255, 255, 255));
        jFil.setBorder(null);

        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMPRIMIR(evt);
            }
        });

        jCilindros.setEditable(false);
        jCilindros.setBackground(new java.awt.Color(255, 255, 255));
        jCilindros.setBorder(null);

        jCel.setEditable(false);
        jCel.setBackground(new java.awt.Color(255, 255, 255));
        jCel.setBorder(null);

        jPlacitos.setEditable(false);
        jPlacitos.setBackground(new java.awt.Color(255, 255, 255));
        jPlacitos.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("LABORATORIO DE ANALISIS CLINICO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Dra. Sara Mercedes Vargas de Castillo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Bioquimica Farmaceutica");

        jLabel11.setText("Medico Solicitante: ");

        jLabel12.setText("Examen Solicitado:");

        jLabel1.setText("Hematies:");

        jLabel13.setText("Paciente:");

        jLabel2.setText("Placitos:");

        jLabel14.setText("Fecha:");

        jLabel3.setText("Cel. Epiteliales:");

        jTextField8.setBorder(null);

        jLabel4.setText("Fil. Mucosas");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/asdqwe.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout imprimirLayout = new javax.swing.GroupLayout(imprimir);
        imprimir.setLayout(imprimirLayout);
        imprimirLayout.setHorizontalGroup(
            imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpaciente)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHematies, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPlacitos)
                            .addComponent(jFil)
                            .addComponent(jCristales)
                            .addComponent(jBacterias)
                            .addComponent(jCilindros)
                            .addComponent(jCel))))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(245, 245, 245))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(101, 101, 101)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(160, 160, 160))
        );
        imprimirLayout.setVerticalGroup(
            imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jHematies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPlacitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCristales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jCilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jBacterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(jButton1)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IMPRIMIR(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMPRIMIR
       /* PrinterJob job = PrinterJob.getPrinterJob();
        
        job.setPrintable(imprimir);
        if(job.printDialog()){
        } */
       try
       {
           PrinterJob gap = PrinterJob.getPrinterJob();
           gap.setPrintable(this);
           boolean top = gap.printDialog();
           if(top)
           {
               gap.print();
           }
       }
       catch(PrinterException pex)
       {
           JOptionPane.showMessageDialog(null, "ERRO",""+pex, JOptionPane.INFORMATION_MESSAGE);                 
       }
    }//GEN-LAST:event_IMPRIMIR

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imprimir;
    private javax.swing.JTextField jBacterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCel;
    private javax.swing.JTextField jCilindros;
    private javax.swing.JTextField jCristales;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JTextField jFil;
    private javax.swing.JTextField jHematies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPlacitos;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtpaciente;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException 
    {
        if(index>0)
        {
            return NO_SUCH_PAGE;  
        }   
            Graphics2D hwb = (Graphics2D) graf;
            hwb.translate(pagfor.getImageableX() + 30, pagfor.getImageableY() + 30);
            hwb.scale(1.0, 1.0);
            imprimir.printAll(hwb);
        return PAGE_EXISTS;
    }
}
