/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;
import control.AdmConsulta_Medica;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.print.Printable;
import java.awt.*;
import java.awt.print.*;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import javafx.print.PrinterJob.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author DoTa_
 */

public class EX_QUI_SAN extends javax.swing.JFrame implements Printable
{
private AdmConsulta_Medica  admConsulta_Medica= AdmConsulta_Medica.getAdmConsulta_Medica();
   
    /**
     * Creates new form EX_MICRO
     */
    public EX_QUI_SAN() {
        initComponents();

        this.setLocationRelativeTo(null);
        admConsulta_Medica.llenarCriteriol(jHematies,jPlacitos,jBacterias,jCilindros,jCristales,jCel,jFil,jNitritos,JCuerpos,JHemoglobina,jleucocitos,jasc,jAlbuminas,jldl);
        txtpaciente.setText(""+admConsulta_Medica.getPacientes().
        get(admConsulta_Medica.getIndexPaciente()).getNombre()+" "+admConsulta_Medica.getPacientes().get(admConsulta_Medica.getIndexPaciente()).getApellido());
        //Color fondoPrincipal = new Color(140, 174, 212);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimir = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpaciente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jHematies = new javax.swing.JTextField();
        jBacterias = new javax.swing.JTextField();
        jCristales = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jFil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCilindros = new javax.swing.JTextField();
        jCel = new javax.swing.JTextField();
        jPlacitos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jNitritos = new javax.swing.JTextField();
        JCuerpos = new javax.swing.JTextField();
        JHemoglobina = new javax.swing.JTextField();
        jleucocitos = new javax.swing.JTextField();
        jasc = new javax.swing.JTextField();
        jAlbuminas = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jldl = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imprimir.setBackground(new java.awt.Color(255, 255, 255));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("QUÍMICA SANGUINA");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel5.setText("Colesterol:");

        txtpaciente.setEditable(false);
        txtpaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtpaciente.setBorder(null);

        jLabel6.setText("Triglicéridos:");

        jLabel7.setText("TGP:");

        jHematies.setEditable(false);
        jHematies.setBackground(new java.awt.Color(255, 255, 255));
        jHematies.setBorder(null);

        jBacterias.setEditable(false);
        jBacterias.setBackground(new java.awt.Color(255, 255, 255));
        jBacterias.setBorder(null);

        jCristales.setEditable(false);
        jCristales.setBackground(new java.awt.Color(255, 255, 255));
        jCristales.setBorder(null);

        jFil.setEditable(false);
        jFil.setBackground(new java.awt.Color(255, 255, 255));
        jFil.setBorder(null);

        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMPRIMIR(evt);
            }
        });

        jCilindros.setEditable(false);
        jCilindros.setBackground(new java.awt.Color(255, 255, 255));
        jCilindros.setBorder(null);

        jCel.setEditable(false);
        jCel.setBackground(new java.awt.Color(255, 255, 255));
        jCel.setBorder(null);

        jPlacitos.setEditable(false);
        jPlacitos.setBackground(new java.awt.Color(255, 255, 255));
        jPlacitos.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("LABORATORIO DE ANALISIS CLINICO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Dra. Sara Mercedes Vargas de Castillo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Bioquimica Farmaceutica");

        jLabel11.setText("Medico Solicitante: ");

        jLabel12.setText("Examen Solicitado:");

        jLabel1.setText("Glicemia:");

        jLabel13.setText("Paciente:");

        jLabel2.setText("Urea:");

        jLabel14.setText("Fecha:");

        jLabel3.setText("Creatinina:");

        jTextField8.setBorder(null);

        jLabel4.setText("Ac.Urico:");

        jLabel15.setText("TGO:");

        jLabel16.setText("F.Alcalina");

        jLabel17.setText("B. Total:");

        jLabel18.setText("B. Directa:");

        jLabel19.setText("B. Indirecta:");

        jLabel20.setText("HDL:");

        jNitritos.setEditable(false);
        jNitritos.setBackground(new java.awt.Color(255, 255, 255));
        jNitritos.setBorder(null);

        JCuerpos.setEditable(false);
        JCuerpos.setBackground(new java.awt.Color(255, 255, 255));
        JCuerpos.setBorder(null);

        JHemoglobina.setEditable(false);
        JHemoglobina.setBackground(new java.awt.Color(255, 255, 255));
        JHemoglobina.setBorder(null);

        jleucocitos.setEditable(false);
        jleucocitos.setBackground(new java.awt.Color(255, 255, 255));
        jleucocitos.setBorder(null);

        jasc.setEditable(false);
        jasc.setBackground(new java.awt.Color(255, 255, 255));
        jasc.setBorder(null);

        jAlbuminas.setEditable(false);
        jAlbuminas.setBackground(new java.awt.Color(255, 255, 255));
        jAlbuminas.setBorder(null);

        jLabel21.setText("LDL:");

        jldl.setEditable(false);
        jldl.setBackground(new java.awt.Color(255, 255, 255));
        jldl.setBorder(null);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\DoTa_\\OneDrive\\Escritorio\\asdqwe.jpg")); // NOI18N
        jLabel22.setText("jLabel22");

        javax.swing.GroupLayout imprimirLayout = new javax.swing.GroupLayout(imprimir);
        imprimir.setLayout(imprimirLayout);
        imprimirLayout.setHorizontalGroup(
            imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(200, 200, 200))
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimirLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addGroup(imprimirLayout.createSequentialGroup()
                                            .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel1))
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel21))
                                            .addGap(18, 18, 18)
                                            .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtpaciente)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jHematies, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jPlacitos)
                                                .addComponent(jFil)
                                                .addComponent(jCristales)
                                                .addComponent(jBacterias)
                                                .addComponent(jCilindros)
                                                .addComponent(jCel)
                                                .addComponent(jNitritos, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(JCuerpos)
                                                .addComponent(JHemoglobina)
                                                .addComponent(jleucocitos)
                                                .addComponent(jasc)
                                                .addComponent(jAlbuminas)
                                                .addComponent(jldl)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(333, 333, 333)))
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        imprimirLayout.setVerticalGroup(
            imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jHematies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPlacitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(imprimirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCristales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jCilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jBacterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jNitritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(JCuerpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(JHemoglobina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jleucocitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAlbuminas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jldl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IMPRIMIR(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMPRIMIR
       /* PrinterJob job = PrinterJob.getPrinterJob();
        
        job.setPrintable(imprimir);
        if(job.printDialog()){
        } */
       try
       {
           PrinterJob gap = PrinterJob.getPrinterJob();
           gap.setPrintable(this);
           boolean top = gap.printDialog();
           if(top)
           {
               gap.print();
           }
       }
       catch(PrinterException pex)
       {
           JOptionPane.showMessageDialog(null, "ERRO",""+pex, JOptionPane.INFORMATION_MESSAGE);                 
       }
    }//GEN-LAST:event_IMPRIMIR

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JCuerpos;
    private javax.swing.JTextField JHemoglobina;
    private javax.swing.JPanel imprimir;
    private javax.swing.JTextField jAlbuminas;
    private javax.swing.JTextField jBacterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCel;
    private javax.swing.JTextField jCilindros;
    private javax.swing.JTextField jCristales;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JTextField jFil;
    private javax.swing.JTextField jHematies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNitritos;
    private javax.swing.JTextField jPlacitos;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jasc;
    private javax.swing.JTextField jldl;
    private javax.swing.JTextField jleucocitos;
    private javax.swing.JTextField txtpaciente;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException 
    {
        if(index>0)
        {
            return NO_SUCH_PAGE;  
        }   
            Graphics2D hwb = (Graphics2D) graf;
            hwb.translate(pagfor.getImageableX() + 30, pagfor.getImageableY() + 30);
            hwb.scale(1.0, 1.0);
            imprimir.printAll(hwb);
        return PAGE_EXISTS;
    }
}
