/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import control.admAgenda;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres Cox
 */
public class FrmAgendaOmar extends javax.swing.JFrame {
admAgenda admagenda = admAgenda.getadmAgenda();
    int AnioFixo=0, MesFixo=0, DiaFixo=0;
    int AnioAltera=0, MesAltera=0, DiaAltera=0;
    int valorSelecionado=0,DiaClic=0;
    public String codigo;
    public String cedula;
    public String nombre;
    public Date f=new Date();
    public String ob;
    public String fechaDia="";
    /**
     * Creates new form FrmAgendaOmar
     */
    public FrmAgendaOmar() {
        initComponents();
        this.setLocationRelativeTo(null);
        calendario_evet();
        InicializarCalendario();
        Calendario();
        BorrarContenido();
        admagenda.llenarAgenda(this.jtagenda);
    }
       private void BorrarContenido() {
        DefaultTableModel modelo = (DefaultTableModel) jtagenda.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jComboMeses = new javax.swing.JComboBox<>();
        jComboAnio = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        Lunes = new javax.swing.JLabel();
        Martes = new javax.swing.JLabel();
        Miercoles = new javax.swing.JLabel();
        Jueves = new javax.swing.JLabel();
        Viernes = new javax.swing.JLabel();
        Sabado = new javax.swing.JLabel();
        Domingo = new javax.swing.JLabel();
        T1 = new javax.swing.JLabel();
        T2 = new javax.swing.JLabel();
        T3 = new javax.swing.JLabel();
        T4 = new javax.swing.JLabel();
        T5 = new javax.swing.JLabel();
        T6 = new javax.swing.JLabel();
        T7 = new javax.swing.JLabel();
        T8 = new javax.swing.JLabel();
        T9 = new javax.swing.JLabel();
        T10 = new javax.swing.JLabel();
        T11 = new javax.swing.JLabel();
        T12 = new javax.swing.JLabel();
        T13 = new javax.swing.JLabel();
        T14 = new javax.swing.JLabel();
        T20 = new javax.swing.JLabel();
        T16 = new javax.swing.JLabel();
        T18 = new javax.swing.JLabel();
        T19 = new javax.swing.JLabel();
        T21 = new javax.swing.JLabel();
        T17 = new javax.swing.JLabel();
        T15 = new javax.swing.JLabel();
        T22 = new javax.swing.JLabel();
        T23 = new javax.swing.JLabel();
        T24 = new javax.swing.JLabel();
        T25 = new javax.swing.JLabel();
        T26 = new javax.swing.JLabel();
        T27 = new javax.swing.JLabel();
        T28 = new javax.swing.JLabel();
        T29 = new javax.swing.JLabel();
        T30 = new javax.swing.JLabel();
        T31 = new javax.swing.JLabel();
        T32 = new javax.swing.JLabel();
        T33 = new javax.swing.JLabel();
        T34 = new javax.swing.JLabel();
        T35 = new javax.swing.JLabel();
        T36 = new javax.swing.JLabel();
        T37 = new javax.swing.JLabel();
        T38 = new javax.swing.JLabel();
        T39 = new javax.swing.JLabel();
        T40 = new javax.swing.JLabel();
        T41 = new javax.swing.JLabel();
        T42 = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();
        jLabelDiaSemanaP1 = new javax.swing.JLabel();
        jlabelDiaP1 = new javax.swing.JLabel();
        jLabelMesP1 = new javax.swing.JLabel();
        labelAñop1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEntregado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtagenda = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(883, 787));

        jLayeredPane2.setBackground(new java.awt.Color(255, 252, 218));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.setOpaque(true);

        jComboMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Juno", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMesesActionPerformed(evt);
            }
        });

        jComboAnio.setEditable(true);
        jComboAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAnioActionPerformed(evt);
            }
        });

        jSpinner1.setToolTipText("");
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        Lunes.setBackground(new java.awt.Color(102, 255, 255));
        Lunes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lunes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lunes.setText("Lun");
        Lunes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Lunes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lunes.setOpaque(true);

        Martes.setBackground(new java.awt.Color(102, 255, 255));
        Martes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Martes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Martes.setText("Mar");
        Martes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Martes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Martes.setOpaque(true);

        Miercoles.setBackground(new java.awt.Color(102, 255, 255));
        Miercoles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Miercoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Miercoles.setText("Mié");
        Miercoles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Miercoles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Miercoles.setOpaque(true);

        Jueves.setBackground(new java.awt.Color(102, 255, 255));
        Jueves.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jueves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jueves.setText("Jue");
        Jueves.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jueves.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Jueves.setOpaque(true);

        Viernes.setBackground(new java.awt.Color(102, 255, 255));
        Viernes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Viernes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Viernes.setText("Vie");
        Viernes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Viernes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Viernes.setOpaque(true);

        Sabado.setBackground(new java.awt.Color(102, 255, 255));
        Sabado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sabado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sabado.setText("Sáb");
        Sabado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sabado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sabado.setOpaque(true);

        Domingo.setBackground(new java.awt.Color(102, 255, 255));
        Domingo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Domingo.setForeground(new java.awt.Color(255, 0, 51));
        Domingo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Domingo.setText("Dom");
        Domingo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Domingo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Domingo.setOpaque(true);

        T1.setBackground(new java.awt.Color(204, 204, 204));
        T1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1.setText("0");
        T1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T2.setBackground(new java.awt.Color(204, 204, 204));
        T2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2.setText("0");
        T2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T3.setBackground(new java.awt.Color(204, 204, 204));
        T3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3.setText("0");
        T3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T4.setBackground(new java.awt.Color(204, 204, 204));
        T4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4.setText("0");
        T4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T5.setBackground(new java.awt.Color(204, 204, 204));
        T5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5.setText("0");
        T5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T6.setBackground(new java.awt.Color(204, 204, 204));
        T6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T6.setText("0");
        T6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        T6.setOpaque(true);

        T7.setBackground(new java.awt.Color(204, 204, 204));
        T7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T7.setText("0");
        T7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T8.setBackground(new java.awt.Color(204, 204, 204));
        T8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T8.setText("0");
        T8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T9.setBackground(new java.awt.Color(204, 204, 204));
        T9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T9.setText("0");
        T9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T10.setBackground(new java.awt.Color(204, 204, 204));
        T10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T10.setText("0");
        T10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T11.setBackground(new java.awt.Color(204, 204, 204));
        T11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T11.setText("0");
        T11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T12.setBackground(new java.awt.Color(204, 204, 204));
        T12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T12.setText("0");
        T12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T13.setBackground(new java.awt.Color(204, 204, 204));
        T13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T13.setText("0");
        T13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T14.setBackground(new java.awt.Color(204, 204, 204));
        T14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T14.setText("0");
        T14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T20.setBackground(new java.awt.Color(204, 204, 204));
        T20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T20.setText("0");
        T20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T16.setBackground(new java.awt.Color(204, 204, 204));
        T16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T16.setText("0");
        T16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T18.setBackground(new java.awt.Color(204, 204, 204));
        T18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T18.setText("0");
        T18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T19.setBackground(new java.awt.Color(204, 204, 204));
        T19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T19.setText("0");
        T19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T21.setBackground(new java.awt.Color(204, 204, 204));
        T21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T21.setText("0");
        T21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T17.setBackground(new java.awt.Color(204, 204, 204));
        T17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T17.setText("0");
        T17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T15.setBackground(new java.awt.Color(204, 204, 204));
        T15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T15.setText("0");
        T15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T22.setBackground(new java.awt.Color(204, 204, 204));
        T22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T22.setText("0");
        T22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T23.setBackground(new java.awt.Color(204, 204, 204));
        T23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T23.setText("0");
        T23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T24.setBackground(new java.awt.Color(204, 204, 204));
        T24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T24.setText("0");
        T24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T25.setBackground(new java.awt.Color(204, 204, 204));
        T25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T25.setText("0");
        T25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T26.setBackground(new java.awt.Color(204, 204, 204));
        T26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T26.setText("0");
        T26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T27.setBackground(new java.awt.Color(204, 204, 204));
        T27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T27.setText("0");
        T27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T28.setBackground(new java.awt.Color(204, 204, 204));
        T28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T28.setText("0");
        T28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T29.setBackground(new java.awt.Color(204, 204, 204));
        T29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T29.setText("0");
        T29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T30.setBackground(new java.awt.Color(204, 204, 204));
        T30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T30.setText("0");
        T30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T31.setBackground(new java.awt.Color(204, 204, 204));
        T31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T31.setText("0");
        T31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T32.setBackground(new java.awt.Color(204, 204, 204));
        T32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T32.setText("0");
        T32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T33.setBackground(new java.awt.Color(204, 204, 204));
        T33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T33.setText("0");
        T33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T34.setBackground(new java.awt.Color(204, 204, 204));
        T34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T34.setText("0");
        T34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T35.setBackground(new java.awt.Color(204, 204, 204));
        T35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T35.setText("0");
        T35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T36.setBackground(new java.awt.Color(204, 204, 204));
        T36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T36.setText("0");
        T36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T37.setBackground(new java.awt.Color(204, 204, 204));
        T37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T37.setText("0");
        T37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T38.setBackground(new java.awt.Color(204, 204, 204));
        T38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T38.setText("0");
        T38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T39.setBackground(new java.awt.Color(204, 204, 204));
        T39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T39.setText("0");
        T39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T40.setBackground(new java.awt.Color(204, 204, 204));
        T40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T40.setText("0");
        T40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T41.setBackground(new java.awt.Color(204, 204, 204));
        T41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T41.setText("0");
        T41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        T42.setBackground(new java.awt.Color(204, 204, 204));
        T42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T42.setText("0");
        T42.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLayeredPane2.setLayer(jComboMeses, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jComboAnio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Lunes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Martes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Miercoles, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Jueves, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Viernes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Sabado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Domingo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(T42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jComboMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(T36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(T29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(T22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(T15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addComponent(T37, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T38, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T40, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                                .addComponent(T41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addComponent(T23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(T27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addComponent(T30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(T34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17)
                                                .addComponent(T12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                                .addComponent(T16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(T19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(T20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(T21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(T28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(T35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(Lunes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Martes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jueves, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Viernes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(Sabado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Domingo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lunes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Martes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jueves, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Viernes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sabado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Domingo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T27, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T29, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T35, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T36)
                    .addComponent(T37, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T38, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T39, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T40, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T41, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T42, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Button1.setBackground(new java.awt.Color(255, 0, 0));
        Button1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button1.setText("HOY");
        Button1.setAutoscrolls(true);
        Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        jLabelDiaSemanaP1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabelDiaSemanaP1.setText("Sábado");

        jlabelDiaP1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jlabelDiaP1.setForeground(new java.awt.Color(204, 0, 0));
        jlabelDiaP1.setText("4");

        jLabelMesP1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabelMesP1.setText("Enero");

        labelAñop1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelAñop1.setText("2020");

        btnEliminar.setBackground(new java.awt.Color(255, 255, 153));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 153));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEntregado.setBackground(new java.awt.Color(204, 102, 255));
        btnEntregado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEntregado.setText("Entregado");
        btnEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregadoActionPerformed(evt);
            }
        });

        jButton1.setText("Todas las Citas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtagenda.setAutoCreateRowSorter(true);
        jtagenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtagenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Examen", "Cedula", "Nombre", "Fecha", "Hora", "Observación", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtagenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtagendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtagenda);

        jButton2.setText("ATRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAñop1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlabelDiaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDiaSemanaP1))
                    .addComponent(jLabelMesP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEntregado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDiaSemanaP1)
                        .addGap(23, 23, 23)
                        .addComponent(jlabelDiaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMesP1)
                        .addGap(31, 31, 31)
                        .addComponent(labelAñop1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(430, 430, 430))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(307, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEntregado)
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(11, 11, 11)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtagendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtagendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtagendaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BorrarContenido();
        admagenda.llenarAgenda(this.jtagenda);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregadoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jtagenda.getModel();
        int fila = jtagenda.getSelectedRow();
        if (fila >= 0) {
            String C = jtagenda.getValueAt(fila, 0).toString();
            int c = Integer.parseInt(C);
            admagenda.entregar(c);
            BorrarContenido();
            admagenda.llenarAgenda(this.jtagenda);
        } else {
            JOptionPane.showMessageDialog(null, "No Selecciono Ninguna Fila", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntregadoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jtagenda.getModel();
        SimpleDateFormat formatodeltexto = new SimpleDateFormat("yyyyy-MM-dd");
        int fila = jtagenda.getSelectedRow();
        if (fila >= 0) {
            try{
                this.codigo=jtagenda.getValueAt(fila, 0).toString();
                this.cedula=jtagenda.getValueAt(fila, 1).toString();
                this.nombre =jtagenda.getValueAt(fila, 2).toString();
                String fecha = jtagenda.getValueAt(fila, 3).toString().trim();
                Date dato = null;
                try {
                    dato = (Date) formatodeltexto.parse(fecha);
                    this.f=dato;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                this.ob =jtagenda.getValueAt(fila, 5).toString();
                FrmRegistros frmreg = new FrmRegistros(this, true);
                frmreg.Rcedula=cedula;
                frmreg.Rcodigo=codigo;
                frmreg.Rnombre=nombre;
                frmreg.Rob=ob;
                frmreg.fe=f;
                frmreg.setVisible(true);
            }catch(NullPointerException d){
                JOptionPane.showMessageDialog(null, "No hay Registro", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No Selecciono Ninguna Fila", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int codigo;
        DefaultTableModel modelo = (DefaultTableModel) jtagenda.getModel();
        int fila = jtagenda.getSelectedRow();
        if (fila >= 0) {
            codigo = Integer.parseInt(jtagenda.getValueAt(fila, 0).toString());
            admagenda.eliminar(codigo);
            BorrarContenido();
            admagenda.llenarAgenda(this.jtagenda);
        } else {
            JOptionPane.showMessageDialog(null, "No Selecciono Ninguna Fila", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        InicializarCalendario();
        Calendario();
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseExited
        // TODO add your handling code here:
        Button1.setBorder(null);
    }//GEN-LAST:event_Button1MouseExited

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseEntered
        // TODO add your handling code here:
        Button1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_Button1MouseEntered

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:

        valorSelecionado=Integer.parseInt(jSpinner1.getValue().toString());
        int x = jComboMeses.getSelectedIndex();
        int anio = Integer.parseInt(jComboAnio.getSelectedItem().toString());

        if (valorSelecionado == -1) {
            if (jComboMeses.getSelectedIndex() != 11) {
                jComboMeses.setSelectedIndex(x + 1);
            } else {
                jComboMeses.setSelectedIndex(0);
                anio = anio + 1;
                jComboAnio.setSelectedItem(anio);
            }
        }

        if(valorSelecionado==1){
            if (jComboMeses.getSelectedIndex() != 0) {
                jComboMeses.setSelectedIndex(x - 1);
            } else {
                jComboMeses.setSelectedIndex(11);
                anio = anio - 1;
                jComboAnio.setSelectedItem(anio);
            }
        }
        jSpinner1.setValue(0);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jComboAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAnioActionPerformed
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(jComboAnio.getSelectedItem().toString());
            DiaAltera=DiaFixo;
            Calendario();
            labelAñop1.setText(jComboAnio.getSelectedItem().toString());
        }catch(Exception e){
            jComboAnio.setSelectedItem(AnioFixo);
        }
    }//GEN-LAST:event_jComboAnioActionPerformed

    private void jComboMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMesesActionPerformed
        // TODO add your handling code here:
        DiaAltera = DiaFixo;
        Calendario();
    }//GEN-LAST:event_jComboMesesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JLabel Domingo;
    private javax.swing.JLabel Jueves;
    private javax.swing.JLabel Lunes;
    private javax.swing.JLabel Martes;
    private javax.swing.JLabel Miercoles;
    private javax.swing.JLabel Sabado;
    private javax.swing.JLabel T1;
    private javax.swing.JLabel T10;
    private javax.swing.JLabel T11;
    private javax.swing.JLabel T12;
    private javax.swing.JLabel T13;
    private javax.swing.JLabel T14;
    private javax.swing.JLabel T15;
    private javax.swing.JLabel T16;
    private javax.swing.JLabel T17;
    private javax.swing.JLabel T18;
    private javax.swing.JLabel T19;
    private javax.swing.JLabel T2;
    private javax.swing.JLabel T20;
    private javax.swing.JLabel T21;
    private javax.swing.JLabel T22;
    private javax.swing.JLabel T23;
    private javax.swing.JLabel T24;
    private javax.swing.JLabel T25;
    private javax.swing.JLabel T26;
    private javax.swing.JLabel T27;
    private javax.swing.JLabel T28;
    private javax.swing.JLabel T29;
    private javax.swing.JLabel T3;
    private javax.swing.JLabel T30;
    private javax.swing.JLabel T31;
    private javax.swing.JLabel T32;
    private javax.swing.JLabel T33;
    private javax.swing.JLabel T34;
    private javax.swing.JLabel T35;
    private javax.swing.JLabel T36;
    private javax.swing.JLabel T37;
    private javax.swing.JLabel T38;
    private javax.swing.JLabel T39;
    private javax.swing.JLabel T4;
    private javax.swing.JLabel T40;
    private javax.swing.JLabel T41;
    private javax.swing.JLabel T42;
    private javax.swing.JLabel T5;
    private javax.swing.JLabel T6;
    private javax.swing.JLabel T7;
    private javax.swing.JLabel T8;
    private javax.swing.JLabel T9;
    private javax.swing.JLabel Viernes;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEntregado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboAnio;
    private javax.swing.JComboBox<String> jComboMeses;
    private javax.swing.JLabel jLabelDiaSemanaP1;
    private javax.swing.JLabel jLabelMesP1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jlabelDiaP1;
    private javax.swing.JTable jtagenda;
    private javax.swing.JLabel labelAñop1;
    // End of variables declaration//GEN-END:variables
public void InicializarCalendario(){
    SimpleDateFormat Anio = new SimpleDateFormat("YYYY");
    SimpleDateFormat Mes = new SimpleDateFormat("MM");
    SimpleDateFormat Dia = new SimpleDateFormat("dd");
    
    AnioFixo=Integer.parseInt(Anio.format(new Date()));
    MesFixo=Integer.parseInt(Mes.format(new Date()));
    DiaFixo=Integer.parseInt(Dia.format(new Date()));
    
//JOptionPane.showMessageDialog(null, DiaFixo+"/"+MesFixo+"/"+AnioFixo);
    int AnioMaximo = AnioFixo + 30;
    for (int i = 2015; i < AnioMaximo; i++) {
        jComboAnio.addItem("" + i);
    }
    jComboAnio.setSelectedItem(AnioFixo);

if(MesFixo==1){
    jComboMeses.setSelectedIndex(0);
}else if(MesFixo==2){
    jComboMeses.setSelectedIndex(1);
}else if(MesFixo==3){
    jComboMeses.setSelectedIndex(2);
}else if(MesFixo==4){
    jComboMeses.setSelectedIndex(3);
}else if(MesFixo==5){
    jComboMeses.setSelectedIndex(4);
}else if(MesFixo==6){
    jComboMeses.setSelectedIndex(5);
}else if(MesFixo==7){
    jComboMeses.setSelectedIndex(6);
}else if(MesFixo==8){
    jComboMeses.setSelectedIndex(7);
}else if(MesFixo==9){
    jComboMeses.setSelectedIndex(8);
}else if(MesFixo==10){
    jComboMeses.setSelectedIndex(9);
}else if(MesFixo==11){
    jComboMeses.setSelectedIndex(10);
}else if(MesFixo==12){
    jComboMeses.setSelectedIndex(11);
}

}

public void Calendario(){
T1.setText(""); T2.setText(""); T3.setText(""); T4.setText("");
T5.setText(""); T6.setText(""); T7.setText(""); T8.setText("");
T9.setText(""); T10.setText(""); T11.setText(""); T12.setText("");
T13.setText(""); T14.setText(""); T15.setText(""); T16.setText("");
T17.setText(""); T18.setText(""); T9.setText(""); T20.setText("");
T21.setText(""); T22.setText(""); T23.setText(""); T24.setText("");
T25.setText(""); T26.setText(""); T27.setText(""); T28.setText("");
T29.setText(""); T30.setText(""); T31.setText(""); T32.setText("");
T33.setText(""); T34.setText(""); T35.setText(""); T36.setText("");
T37.setText(""); T38.setText(""); T39.setText(""); T40.setText("");
T41.setText(""); T42.setText("");

    DiaAltera = DiaFixo;
    MesAltera = jComboMeses.getSelectedIndex();
    AnioAltera = Integer.parseInt(jComboAnio.getSelectedItem().toString());

        int totalDiaMes = 0;

        if (MesAltera == 0) {
            totalDiaMes = 31;
        } else if (MesAltera == 1) {
            int resultado = (AnioAltera % 4);
            if (resultado == 0) {
                totalDiaMes = 29;
            } else {
                totalDiaMes = 28;
            }
        } else if (MesAltera == 2) {
            totalDiaMes = 31;
        } else if (MesAltera == 3) {
            totalDiaMes = 30;
        } else if (MesAltera == 4) {
            totalDiaMes = 31;
        } else if (MesAltera == 5) {
            totalDiaMes = 30;
        } else if (MesAltera == 6) {
            totalDiaMes = 31;
        } else if (MesAltera == 7) {
            totalDiaMes = 31;
        } else if (MesAltera == 8) {
            totalDiaMes = 30;
        }else if (MesAltera == 9) {
            totalDiaMes = 31;
        }else if (MesAltera == 10) {
            totalDiaMes = 30;
        }else if (MesAltera == 11) {
            totalDiaMes = 31;
        }

       Calendar calendar = Calendar.getInstance();
       calendar.set(AnioAltera, MesAltera, 1);

       int setaDia=0;
       int Semana = calendar.get(Calendar.DAY_OF_WEEK);
//       JOptionPane.showMessageDialog(null, Semana);
       if(Semana==Calendar.MONDAY){
           setaDia=1;
       }else if(Semana==Calendar.TUESDAY){
           setaDia=2;
       }else if(Semana==Calendar.WEDNESDAY){
           setaDia=3;
       }else if(Semana==Calendar.THURSDAY){
           setaDia=4;
       }else if(Semana==Calendar.FRIDAY){
           setaDia=5;
       }else if(Semana==Calendar.SATURDAY){
           setaDia=6;
       }else if(Semana==Calendar.SUNDAY){
           setaDia=7;
       }
     
       for(int i=1;i<=totalDiaMes;i++){
           switch (setaDia) {
               case 1:
                  dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T1);
                   break;
               case 2:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T2);
                   break;
               case 3:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T3);
                   break;
               case 4:
                  
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T4);
                   break;
               case 5:
                  dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T5);
                   break;
               case 6:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T6);
                   break;
               case 7:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T7);
                   break;
               case 8:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T8);
                   break;
               case 9:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T9);
                   break;
               case 10:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T10);
                   break;
               case 11:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T11);
                   break;
               case 12:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T12);
                   break;
               case 13:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T13);
                   break;
               case 14:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T14);
                   break;
               case 15:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T15);
                   break;
               case 16:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T16);
                   break;
               case 17:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T17);
                   break;
               case 18:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T18);
                   break;
               case 19:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T19);
                   break;
               case 20:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T20);
                   break;
               case 21:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T21);
                   break;
               case 22:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T22);
                   break;
               case 23:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T23);
                   break;
               case 24:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T24);
                   break;
               case 25:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T25);
                   break;
               case 26:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T26);
                   break;
               case 27:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T27);
                   break;
               case 28:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T28);
                   break;
               case 29:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T29);
                   break;
               case 30:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T30);
                   break;
               case 31:
                  dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T31);
                   break;
               case 32:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T32);
                   break;
               case 33:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T33);
                   break;
               case 34:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T34);
                   break;
               case 35:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T35);
                   break;
               case 36:
                  dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T36);
                   break;
               case 37:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T37);
                   break;
               case 38:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T38);
                   break;
               case 39:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T39);
                   break;
               case 40:
                  dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T40);
                   break;
               case 41:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T41);
                   break;
               case 42:
                   dia(DiaFixo,MesAltera,MesFixo,AnioAltera,AnioFixo, i, T42);
                   break;
           }
           setaDia++;
       }
       if(!"".equals(T1.getText())){
           T1.setOpaque(true);
       }else{
       T1.setOpaque(false);
       }if(!"".equals(T2.getText())){
           T2.setOpaque(true);
       }else{
       T2.setOpaque(false);
       }if(!"".equals(T3.getText())){
           T3.setOpaque(true);
       }else{
       T3.setOpaque(false);
       }if(!"".equals(T4.getText())){
           T4.setOpaque(true);
       }else{
       T4.setOpaque(false);
       }if(!"".equals(T5.getText())){
           T5.setOpaque(true);
       }else{
       T5.setOpaque(false);
       }if(!"".equals(T6.getText())){
           T6.setOpaque(true);
       }else{
       T6.setOpaque(false);
       }if(!"".equals(T7.getText())){
           T7.setOpaque(true);
       }else{
       T7.setOpaque(false);
       }if(!"".equals(T8.getText())){
           T8.setOpaque(true);
       }else{
       T8.setOpaque(false);
       }if(!"".equals(T9.getText())){
           T9.setOpaque(true);
       }else{
       T9.setOpaque(false);
       }if(!"".equals(T10.getText())){
           T10.setOpaque(true);
       }else{
       T10.setOpaque(false);
       }if(!"".equals(T11.getText())){
           T11.setOpaque(true);
       }else{
       T11.setOpaque(false);
       }if(!"".equals(T12.getText())){
           T12.setOpaque(true);
       }else{
       T12.setOpaque(false);
       }if(!"".equals(T13.getText())){
           T13.setOpaque(true);
       }else{
       T13.setOpaque(false);
       }if(!"".equals(T14.getText())){
           T14.setOpaque(true);
       }else{
       T14.setOpaque(false);
       }if(!"".equals(T15.getText())){
           T15.setOpaque(true);
       }else{
       T15.setOpaque(false);
       }if(!"".equals(T16.getText())){
           T16.setOpaque(true);
       }else{
       T16.setOpaque(false);
       }if(!"".equals(T17.getText())){
           T17.setOpaque(true);
       }else{
       T17.setOpaque(false);
       }if(!"".equals(T18.getText())){
           T18.setOpaque(true);
       }else{
       T18.setOpaque(false);
       }if(!"".equals(T19.getText())){
           T19.setOpaque(true);
       }else{
       T19.setOpaque(false);
       }if(!"".equals(T20.getText())){
           T20.setOpaque(true);
       }else{
       T20.setOpaque(false);
       }if(!"".equals(T21.getText())){
           T21.setOpaque(true);
       }else{
       T21.setOpaque(false);
       }if(!"".equals(T22.getText())){
           T22.setOpaque(true);
       }else{
       T22.setOpaque(false);
       }if(!"".equals(T23.getText())){
           T23.setOpaque(true);
       }else{
       T23.setOpaque(false);
       }if(!"".equals(T24.getText())){
           T24.setOpaque(true);
       }else{
       T24.setOpaque(false);
       }if(!"".equals(T25.getText())){
           T25.setOpaque(true);
       }else{
       T25.setOpaque(false);
       }if(!"".equals(T26.getText())){
           T26.setOpaque(true);
       }else{
       T26.setOpaque(false);
       }if(!"".equals(T27.getText())){
           T27.setOpaque(true);
       }else{
       T27.setOpaque(false);
       }if(!"".equals(T28.getText())){
           T28.setOpaque(true);
       }else{
       T28.setOpaque(false);
       }if(!"".equals(T29.getText())){
           T29.setOpaque(true);
       }else{
       T29.setOpaque(false);
       }if(!"".equals(T30.getText())){
           T30.setOpaque(true);
       }else{
       T30.setOpaque(false);
       }if(!"".equals(T31.getText())){
           T31.setOpaque(true);
       }else{
       T31.setOpaque(false);
       }if(!"".equals(T32.getText())){
           T32.setOpaque(true);
       }else{
       T32.setOpaque(false);
       }if(!"".equals(T33.getText())){
           T33.setOpaque(true);
       }else{
       T33.setOpaque(false);
       }if(!"".equals(T34.getText())){
           T34.setOpaque(true);
       }else{
       T34.setOpaque(false);
       }if(!"".equals(T35.getText())){
           T35.setOpaque(true);
       }else{
       T35.setOpaque(false);
       }if(!"".equals(T36.getText())){
           T36.setOpaque(true);
       }else{
       T36.setOpaque(false);
       }if(!"".equals(T37.getText())){
           T37.setOpaque(true);
       }else{
       T37.setOpaque(false);
       }if(!"".equals(T38.getText())){
           T38.setOpaque(true);
       }else{
       T38.setOpaque(false);
       }if(!"".equals(T39.getText())){
           T39.setOpaque(true);
       }else{
       T39.setOpaque(false);
       }if(!"".equals(T40.getText())){
           T40.setOpaque(true);
       }else{
       T40.setOpaque(false);
       }if(!"".equals(T41.getText())){
           T41.setOpaque(true);
       }else{
       T41.setOpaque(false);
       }if(!"".equals(T42.getText())){
           T42.setOpaque(true);
       }else{
       T42.setOpaque(false);
       }
       VerificarSemana();
    }

public void VerificarSemana(){
try{
    
    if(MesAltera!=MesFixo-1 && DiaClic!=0){
        DiaAltera=1;
    }if(AnioAltera!=AnioFixo && DiaClic!=0){
        DiaAltera=1;
    }
    DiaClic=1;
    
    if(DiaAltera==DiaFixo && MesAltera+1 == MesFixo && AnioAltera==AnioFixo){
    jlabelDiaP1.setForeground(Color.red);
    }else{
    jlabelDiaP1.setForeground(Color.black);
    }
    
    
    MesAltera=jComboMeses.getSelectedIndex();
    AnioAltera=Integer.parseInt(jComboAnio.getSelectedItem().toString());

Calendar calendarN = Calendar.getInstance();
calendarN.set(AnioAltera, MesAltera,DiaAltera);

        jLabelMesP1.setText(jComboMeses.getSelectedItem().toString());
        
        jlabelDiaP1.setText(""+DiaAltera);
        
     int semanaN = calendarN.get(Calendar.DAY_OF_WEEK);
    if (semanaN == Calendar.MONDAY) {
        jLabelDiaSemanaP1.setText("Lunes");
    } else if (semanaN == Calendar.TUESDAY) {
        jLabelDiaSemanaP1.setText("Martes");
    } else if (semanaN == Calendar.WEDNESDAY) {
        jLabelDiaSemanaP1.setText("Miércoles");
    } else if (semanaN == Calendar.THURSDAY) {
        jLabelDiaSemanaP1.setText("Jueves");
    } else if (semanaN == Calendar.FRIDAY) {
        jLabelDiaSemanaP1.setText("Viernes");
    } else if (semanaN == Calendar.SATURDAY) {
        jLabelDiaSemanaP1.setText("Sábado");
    } else if (semanaN == Calendar.SUNDAY) {
        jLabelDiaSemanaP1.setText("Domingo");
    }
}catch(Exception e){
System.out.println(e);
}}

public void calendario_evet()
{
eve_dia(T1);
eve_dia(T2);
eve_dia(T3);
eve_dia(T4);
eve_dia(T5);
eve_dia(T6);
eve_dia(T7);
eve_dia(T8);
eve_dia(T9);
eve_dia(T10);
eve_dia(T11);
eve_dia(T12);
eve_dia(T13);
eve_dia(T14);
eve_dia(T15);
eve_dia(T16);
eve_dia(T17);
eve_dia(T18);
eve_dia(T19);
eve_dia(T20);
eve_dia(T21);
eve_dia(T22);
eve_dia(T23);
eve_dia(T24);
eve_dia(T25);
eve_dia(T26);
eve_dia(T27);
eve_dia(T28);
eve_dia(T29);
eve_dia(T30);
eve_dia(T31);
eve_dia(T32);
eve_dia(T33);
eve_dia(T34);
eve_dia(T35);
eve_dia(T36);
eve_dia(T37);
eve_dia(T38);
eve_dia(T39);
eve_dia(T40);
eve_dia(T41);
eve_dia(T42);

}
public void eve_dia(javax.swing.JLabel T){
T.addMouseListener(new java.awt.event.MouseAdapter(){

           public void mouseEntered(java.awt.event.MouseEvent evt){
               if(!"".equals(T.getText())){
                   T.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
               }
           }

           public void mouseExited(java.awt.event.MouseEvent evt){
               T.setBorder(null);
           }

           public void mouseClicked (java.awt.event.MouseEvent evt){
           if(!"".equals(T.getText())){
               jlabelDiaP1.setText(T.getText());
               
               DiaAltera=Integer.parseInt(T.getText());
               String d="",m;
                m = ""+((jComboMeses.getSelectedIndex())+1);
               String a = jComboAnio.getSelectedItem().toString();
               if(DiaAltera>=10){
               d=""+DiaAltera;
               }else if(DiaAltera>=1 && DiaAltera<=9){
               d="0"+DiaAltera;
               }
               if((jComboMeses.getSelectedIndex()+1)>=10){
                 m = ""+((jComboMeses.getSelectedIndex())+1);
                }else if((jComboMeses.getSelectedIndex()+1)>=1&&(jComboMeses.getSelectedIndex()+1)<=9){
                 m = "0"+((jComboMeses.getSelectedIndex())+1);
                }
               DiaClic=0;
               VerificarSemana();
               fechaDia=a+"-"+m+"-"+d;
BorrarContenido();
admagenda.FiltroFecha(jtagenda, fechaDia);
           }
           }
       });
}




public void dia(int DiaFixoo,int MesAlteraa, int MesFixoo, int AnioAlteraa, int AnioFixoo,int i, javax.swing.JLabel T){
T.setText(""+i);
                   if(i==DiaFixoo && MesAlteraa==MesFixoo-1 && AnioAlteraa==AnioFixoo){
                       T.setForeground(Color.red);
                   }else{
                      T.setForeground(Color.black);
                   }
}

}
