/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import control.AdmConsulta_Medica;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hellen
 */
public class FrmPresentar_Historial extends javax.swing.JFrame {
private AdmConsulta_Medica  admConsulta_Medica= AdmConsulta_Medica.getAdmConsulta_Medica();
    /**
     * Creates new form FrmPresentar
     */
    public FrmPresentar_Historial() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        admConsulta_Medica.llenarHistorial(tbPresentacion,"all");
        btnRegistrarConsulta.setEnabled(false);
        lblHistorialPaciente.setText(lblHistorialPaciente.getText()+admConsulta_Medica.getPacientes().
        get(admConsulta_Medica.getIndexPaciente()).getNombre()+" "+admConsulta_Medica.getPacientes().
        get(admConsulta_Medica.getIndexPaciente()).getApellido());
        lblCedula.setText("\nC.I: "+admConsulta_Medica.getPacientes().
        get(admConsulta_Medica.getIndexPaciente()).getCedula());
        
        
        Color fondoPrincipal = new Color(140, 174, 212);
        Color fondoBlanco = new Color(255, 255, 255);
        
        jPanel1.setBackground(fondoPrincipal);
        //tbPaciente.setOpaque(true);
        btnRegistrarConsulta.setBackground(Color.WHITE);
        btnRegistrarConsulta.setOpaque(true);
        btnCancelar.setBackground(fondoBlanco);
        btnCancelar.setOpaque(true);
        tbPresentacion.setFillsViewportHeight(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarConsulta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPresentacion = new javax.swing.JTable();
        lblHistorialPaciente = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presentar información de usuario");

        btnRegistrarConsulta.setText("Presentar información");
        btnRegistrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConsultaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tbPresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Examen", "Fecha", "Código", "Exámen cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPresentacion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPresentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPresentacionMouseClicked(evt);
            }
        });
        tbPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPresentacionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbPresentacion);

        lblHistorialPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistorialPaciente.setText("Historial del paciente: ");

        lblCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnRegistrarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblHistorialPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblHistorialPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConsultaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbPresentacion.getModel();
        admConsulta_Medica.setIndexDetalle_Examenes((int) modelo.getValueAt(tbPresentacion.getSelectedRow(), 2));
        admConsulta_Medica.setIndexFecha((LocalDate)modelo.getValueAt(tbPresentacion.getSelectedRow(), 1));
        admConsulta_Medica.setIndexExamenes((int)modelo.getValueAt(tbPresentacion.getSelectedRow(), 3));
        //admConsulta_Medica.
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        admConsulta_Medica.setIndexPaciente(tbPresentacion.getSelectedRow());
        FrmMostrar_Criterio frmMostrar_Criterio = new FrmMostrar_Criterio();
        frmMostrar_Criterio.setVisible(true);
    }//GEN-LAST:event_btnRegistrarConsultaActionPerformed

    private void tbPresentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPresentacionMouseClicked
        btnRegistrarConsulta.setEnabled(true);
    }//GEN-LAST:event_tbPresentacionMouseClicked

    private void tbPresentacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPresentacionKeyPressed

    }//GEN-LAST:event_tbPresentacionKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
private void borrar(){
        DefaultTableModel modelo=(DefaultTableModel)tbPresentacion.getModel();
        if(modelo.getRowCount()!=0){
            while(modelo.getRowCount()>0)
            {
                modelo.removeRow(0);
            }
        } 
    }
    private int contar(){
        int cantidad=0;
        DefaultTableModel modelo=(DefaultTableModel)tbPresentacion.getModel();
        cantidad=modelo.getRowCount();
        return cantidad;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblHistorialPaciente;
    private javax.swing.JTable tbPresentacion;
    // End of variables declaration//GEN-END:variables
}
