/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import visual.FrmAgenda;
import Model.Usuario;
import control.AdmVentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Andres Cox
 */
public class FrmVentanaPrincipal extends javax.swing.JFrame {
    AdmVentanaPrincipal admVentanaPrincipal = AdmVentanaPrincipal.getAdmVentanaPrincipal();
    public String usuario;

    /**
     * Creates new form FrmVentanaPrincipal
     */
    public FrmVentanaPrincipal() {
        initComponents();
      // control();
        Color  blanco = new Color(255, 255, 255);
        this.getContentPane().setBackground(new Color(140, 174, 212));
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        jPanelContenedor.setBackground(new Color(174, 196, 222));
        jPanelPrincipal.setBackground(blanco);
        jPanelHistorialPaciente.setBackground(blanco);
        jPanelPresentarCitas.setBackground(blanco);
        jPaneRegistro.setBackground(blanco);
        jPanelRegistrarPaciente.setBackground(blanco);
        jPanelAgendarCita.setBackground(blanco);
        jPanelPresentarComprobante.setBackground(blanco);
        /********************************************/
        btnRegistrarAnalisis.setMinimumSize(new Dimension(69, 69));
        btnRegistrarPaciente.setMaximumSize(new Dimension(69, 69));
        
        btnRegistrarCita.setPreferredSize(new Dimension(69, 69));
        
        
        
        /********************************************/
        
        admVentanaPrincipal.llenarlbls(lblPanelControl, lblHelen, btnRegistrarAnalisis, btnRegistrarPaciente, btnRegistrarCita,
                btnHistorial, btnCitas, btnComprobante, btnEmip);
        btnRegistrarAnalisis.setBackground(Color.WHITE);
        btnRegistrarAnalisis.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelContenedor = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPaneRegistro = new javax.swing.JPanel();
        btnRegistrarAnalisis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelAgendarCita = new javax.swing.JPanel();
        btnRegistrarCita = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelRegistrarPaciente = new javax.swing.JPanel();
        btnRegistrarPaciente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanelHistorialPaciente = new javax.swing.JPanel();
        btnHistorial = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanelPresentarCitas = new javax.swing.JPanel();
        btnCitas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanelPresentarComprobante = new javax.swing.JPanel();
        btnComprobante = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblPanelControl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHelen = new javax.swing.JLabel();
        btnEmip = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPrincipal.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 112, 179));
        jLabel5.setText("Registro de información");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 10, 0, 0);
        jPanelPrincipal.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(24, 112, 179));
        jLabel6.setText("Presentar información");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 13, 0, 0);
        jPanelPrincipal.add(jLabel6, gridBagConstraints);

        jPaneRegistro.setBackground(new java.awt.Color(250, 250, 250));

        btnRegistrarAnalisis.setBorder(null);
        btnRegistrarAnalisis.setContentAreaFilled(false);
        btnRegistrarAnalisis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarAnalisis.setFocusPainted(false);
        btnRegistrarAnalisis.setPreferredSize(new java.awt.Dimension(73, 22));
        btnRegistrarAnalisis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/RegistrarAnalisisSeleccion.png"))); // NOI18N
        btnRegistrarAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAnalisisActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registrar análisis");

        javax.swing.GroupLayout jPaneRegistroLayout = new javax.swing.GroupLayout(jPaneRegistro);
        jPaneRegistro.setLayout(jPaneRegistroLayout);
        jPaneRegistroLayout.setHorizontalGroup(
            jPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneRegistroLayout.setVerticalGroup(
            jPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRegistroLayout.createSequentialGroup()
                .addComponent(btnRegistrarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 3, 0, 0);
        jPanelPrincipal.add(jPaneRegistro, gridBagConstraints);

        btnRegistrarCita.setBorder(null);
        btnRegistrarCita.setBorderPainted(false);
        btnRegistrarCita.setContentAreaFilled(false);
        btnRegistrarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCita.setFocusPainted(false);
        btnRegistrarCita.setPreferredSize(new java.awt.Dimension(73, 22));
        btnRegistrarCita.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/RegistrarCitaSelección.png"))); // NOI18N
        btnRegistrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCitaActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agendar cita");

        javax.swing.GroupLayout jPanelAgendarCitaLayout = new javax.swing.GroupLayout(jPanelAgendarCita);
        jPanelAgendarCita.setLayout(jPanelAgendarCitaLayout);
        jPanelAgendarCitaLayout.setHorizontalGroup(
            jPanelAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendarCitaLayout.createSequentialGroup()
                .addGroup(jPanelAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgendarCitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegistrarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        jPanelAgendarCitaLayout.setVerticalGroup(
            jPanelAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendarCitaLayout.createSequentialGroup()
                .addComponent(btnRegistrarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 190, 0, 0);
        jPanelPrincipal.add(jPanelAgendarCita, gridBagConstraints);

        btnRegistrarPaciente.setText("   ");
        btnRegistrarPaciente.setBorder(null);
        btnRegistrarPaciente.setBorderPainted(false);
        btnRegistrarPaciente.setContentAreaFilled(false);
        btnRegistrarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPaciente.setFocusPainted(false);
        btnRegistrarPaciente.setPreferredSize(new java.awt.Dimension(73, 22));
        btnRegistrarPaciente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/RegistrarPacienteSeleccion.png"))); // NOI18N
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrar paciente");

        javax.swing.GroupLayout jPanelRegistrarPacienteLayout = new javax.swing.GroupLayout(jPanelRegistrarPaciente);
        jPanelRegistrarPaciente.setLayout(jPanelRegistrarPacienteLayout);
        jPanelRegistrarPacienteLayout.setHorizontalGroup(
            jPanelRegistrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRegistrarPacienteLayout.setVerticalGroup(
            jPanelRegistrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarPacienteLayout.createSequentialGroup()
                .addComponent(btnRegistrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 182, 0, 0);
        jPanelPrincipal.add(jPanelRegistrarPaciente, gridBagConstraints);

        jPanelHistorialPaciente.setBackground(new java.awt.Color(250, 250, 250));

        btnHistorial.setBorder(null);
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorial.setFocusPainted(false);
        btnHistorial.setPreferredSize(new java.awt.Dimension(73, 22));
        btnHistorial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/HistorialPacienteSeleccion.png"))); // NOI18N
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Historial paciente");

        javax.swing.GroupLayout jPanelHistorialPacienteLayout = new javax.swing.GroupLayout(jPanelHistorialPaciente);
        jPanelHistorialPaciente.setLayout(jPanelHistorialPacienteLayout);
        jPanelHistorialPacienteLayout.setHorizontalGroup(
            jPanelHistorialPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHistorialPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHistorialPacienteLayout.setVerticalGroup(
            jPanelHistorialPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialPacienteLayout.createSequentialGroup()
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 21, 16, 0);
        jPanelPrincipal.add(jPanelHistorialPaciente, gridBagConstraints);

        btnCitas.setText("   ");
        btnCitas.setBorder(null);
        btnCitas.setBorderPainted(false);
        btnCitas.setContentAreaFilled(false);
        btnCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCitas.setFocusPainted(false);
        btnCitas.setPreferredSize(new java.awt.Dimension(73, 22));
        btnCitas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/CitaSeleccion.png"))); // NOI18N
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Presentar citas");

        javax.swing.GroupLayout jPanelPresentarCitasLayout = new javax.swing.GroupLayout(jPanelPresentarCitas);
        jPanelPresentarCitas.setLayout(jPanelPresentarCitasLayout);
        jPanelPresentarCitasLayout.setHorizontalGroup(
            jPanelPresentarCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentarCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPresentarCitasLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(btnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelPresentarCitasLayout.setVerticalGroup(
            jPanelPresentarCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentarCitasLayout.createSequentialGroup()
                .addComponent(btnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 167, 0, 0);
        jPanelPrincipal.add(jPanelPresentarCitas, gridBagConstraints);

        btnComprobante.setBorder(null);
        btnComprobante.setBorderPainted(false);
        btnComprobante.setContentAreaFilled(false);
        btnComprobante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprobante.setFocusPainted(false);
        btnComprobante.setPreferredSize(new java.awt.Dimension(69, 69));
        btnComprobante.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ComprobanteSeleccion.png"))); // NOI18N
        btnComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobanteActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Comprobante");

        javax.swing.GroupLayout jPanelPresentarComprobanteLayout = new javax.swing.GroupLayout(jPanelPresentarComprobante);
        jPanelPresentarComprobante.setLayout(jPanelPresentarComprobanteLayout);
        jPanelPresentarComprobanteLayout.setHorizontalGroup(
            jPanelPresentarComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentarComprobanteLayout.createSequentialGroup()
                .addGroup(jPanelPresentarComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPresentarComprobanteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        jPanelPresentarComprobanteLayout.setVerticalGroup(
            jPanelPresentarComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentarComprobanteLayout.createSequentialGroup()
                .addComponent(btnComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 202, 0, 24);
        jPanelPrincipal.add(jPanelPresentarComprobante, gridBagConstraints);

        lblPanelControl.setText("jLabel1");
        lblPanelControl.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 112, 179));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PANEL DE CONTROL");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEmip.setBorderPainted(false);
        btnEmip.setContentAreaFilled(false);
        btnEmip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmip.setFocusPainted(false);
        btnEmip.setFocusable(false);
        btnEmip.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/EmipSeleccion.png"))); // NOI18N
        btnEmip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmipActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("EMIP");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Entorno de Manejo Integrado de Pacientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHelen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEmip, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblHelen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAnalisisActionPerformed
       this.setVisible(false);
       FrmModuloExamen frmModuloExamen = new FrmModuloExamen();
       this.setVisible(true);
       frmModuloExamen.setVisible(true);
    }//GEN-LAST:event_btnRegistrarAnalisisActionPerformed

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
       this.setVisible(false);
       FrmConsulta_Medica1 frmConsulta_Medica1 = new FrmConsulta_Medica1(this,true);
       frmConsulta_Medica1.setVisible(true);
       this.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        this.setVisible(false);
        FrmPaciente_Con_Examen frmPaciente_Con_Examen = new FrmPaciente_Con_Examen();
        this.setVisible(true);
        frmPaciente_Con_Examen.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnEmipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmipActionPerformed
        FrmProgramadores frmProgramadores = new FrmProgramadores(this,true);
        frmProgramadores.setVisible(true);
    }//GEN-LAST:event_btnEmipActionPerformed

    private void btnComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobanteActionPerformed
        // TODO add your handling code here:                                             
        this.setVisible(false);
        FrmPaciente_Comprobante frmPaciente_Con_Examen = new FrmPaciente_Comprobante();
        this.setVisible(true);
        frmPaciente_Con_Examen.setVisible(true);
    }//GEN-LAST:event_btnComprobanteActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //FrmAgenda frmagenda = new FrmAgenda();
        FrmAgenda frmagenda = new FrmAgenda();
        this.setVisible(true);
        //frmagenda.setVisible(true);
        frmagenda.setVisible(true);
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnRegistrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCitaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmRegistros frmreg = new FrmRegistros(this,true);
        frmreg.setVisible(true);
        this.setVisible(true);

    }//GEN-LAST:event_btnRegistrarCitaActionPerformed
    public void control(){
        Usuario us = new Usuario();
        if(us.getContraseña().equals("EMIASISTENTE")){
            this.btnComprobante.setVisible(false);
            this.btnHistorial.setVisible(false);
            this.btnRegistrarPaciente.setVisible(false);
            this.btnRegistrarAnalisis.setVisible(false);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnComprobante;
    private javax.swing.JButton btnEmip;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRegistrarAnalisis;
    private javax.swing.JButton btnRegistrarCita;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneRegistro;
    private javax.swing.JPanel jPanelAgendarCita;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelHistorialPaciente;
    private javax.swing.JPanel jPanelPresentarCitas;
    private javax.swing.JPanel jPanelPresentarComprobante;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRegistrarPaciente;
    private javax.swing.JLabel lblHelen;
    private javax.swing.JLabel lblPanelControl;
    // End of variables declaration//GEN-END:variables
}
