/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import Datos.UsuarioLogin;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author domar1299
 */
public class Loginn extends javax.swing.JFrame {

   
    public Loginn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_contrasena = new javax.swing.JLabel();
        txt_contrasena = new javax.swing.JPasswordField();
        btn_sesion = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        lbl_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_usuario.setText("USUARIO:");

        lbl_contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_contrasena.setForeground(new java.awt.Color(255, 102, 0));
        lbl_contrasena.setText("CONTRASEÑA:");

        btn_sesion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn_sesion.setForeground(new java.awt.Color(51, 51, 0));
        btn_sesion.setText("Iniciar sesión");
        btn_sesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        btn_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesionActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(51, 51, 0));
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 0)));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        lbl_login.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(255, 153, 51));
        lbl_login.setText("LOGIN DEL SISTEMA EMIP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbl_contrasena)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usuario)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contrasena))
                .addGap(45, 45, 45)
                .addComponent(btn_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesionActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txt_usuario.getText()) && !"".equals(txt_contrasena.getText())) {
            Model.Usuario usuario = new Usuario(0, txt_usuario.getText(), txt_contrasena.getText());
            boolean validarLogin = UsuarioLogin.login(usuario);
            FrmVentanaPrincipal frmvp = new FrmVentanaPrincipal();
            if (validarLogin == true) {
                JOptionPane.showMessageDialog(null, "Ingreso exitoso");
                //PRIVILEGIO ADMINISRADOR
                if (txt_usuario.getText().equals("944366426")) {
                   // frmvp.usuario="Administrador";
                    frmvp.setVisible(true);
                    //PRIVILEGIO USUARIO
                }else if(txt_usuario.getText().equals("930628664")){
                     //    frmvp.usuario="Usuario";
                    frmvp.setVisible(true);

                    //PRIVILEGIO ASISTENTE
                }else if(txt_usuario.getText().equals("986543276")){
                     //frmvp.usuario="Asistente";
                    frmvp.setVisible(true);
                }
                //                Visual.Acceso a= new Acceso();
                //                a.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos para iniciar sesion");
        }

    }//GEN-LAST:event_btn_sesionActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_sesion;
    private javax.swing.JLabel lbl_contrasena;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
